require('dotenv').config();
require('./config/database');

const Company = require('./models/company');

(async function(){
await Company.deleteMany({});
const countries = await Company.create([
{country: 'Afghanistan', sortOrder: 1},
{country: 'Albania', sortOrder: 2},
{country: 'Algeria', sortOrder: 3},
{country: 'AndorraAngola', sortOrder: 4},
// {country: , sortOrder: 5},
// {country: , sortOrder: 6},
// {country: , sortOrder: 7},
// {country: , sortOrder: 8},
// {country: , sortOrder: 9},
// {country: , sortOrder: 10},
// {country: , sortOrder: 11},
// {country: , sortOrder: 12},
// {country: , sortOrder: 13},
// {country: , sortOrder: 14},
// {country: , sortOrder: 15},
// {country: , sortOrder: 16},
// {country: , sortOrder: 17},
// {country: , sortOrder: 18},
// {country: , sortOrder: 19},
// {country: , sortOrder: 20},
// {country: , sortOrder: 21},
// {country: , sortOrder: 22},
// {country: , sortOrder: 23},
// {country: , sortOrder: 24},
// {country: , sortOrder: 25},
// {country: , sortOrder: 26},
// {country: , sortOrder: 27},
// {country: , sortOrder: 28},
// {country: , sortOrder: 29},
// {country: , sortOrder: 30},
// {country: , sortOrder: 31},
// {country: , sortOrder: 32},
// {country: , sortOrder: 33},
// {country: , sortOrder: 34},
// {country: , sortOrder: 35},
// {country: , sortOrder: 36},
// {country: , sortOrder: 37},
// {country: , sortOrder: 38},
// {country: , sortOrder: 39},
// {country: , sortOrder: 40},
// {country: , sortOrder: 41},
// {country: , sortOrder: 42},
// {country: , sortOrder: 43},
// {country: , sortOrder: 44},
// {country: , sortOrder: 45},
// {country: , sortOrder: 46},
// {country: , sortOrder: 47},
// {country: , sortOrder: 48},
// {country: , sortOrder: 49},
// {country: , sortOrder: 50},
// {country: , sortOrder: 51},
// {country: , sortOrder: 52},
// {country: , sortOrder: 53},
// {country: , sortOrder: 54},
// {country: , sortOrder: 55},
// {country: , sortOrder: 56},
// {country: , sortOrder: 57},
// {country: , sortOrder: 58},
// {country: , sortOrder: 59},
// {country: , sortOrder: 60},
// {country: , sortOrder: 61},
// {country: , sortOrder: 62},
// {country: , sortOrder: 63},
// {country: , sortOrder: 64},
// {country: , sortOrder: 66},
// {country: , sortOrder: 67},
// {country: , sortOrder: 68},
// {country: , sortOrder: 69}, //nice 
// {country: , sortOrder: 70},
// {country: , sortOrder: 71},
// {country: , sortOrder: 72},
// {country: , sortOrder: 73},
// {country: , sortOrder: 74},
// {country: , sortOrder: 75},
// {country: , sortOrder: 76},
// {country: , sortOrder: 77},
// {country: , sortOrder: 78},
// {country: , sortOrder: 79},
// {country: , sortOrder: 80},
// {country: , sortOrder: 81},
// {country: , sortOrder: 82},
// {country: , sortOrder: 83},
// {country: , sortOrder: 84},
// {country: , sortOrder: 85},
// {country: , sortOrder: 86},
// {country: , sortOrder: 87},
// {country: , sortOrder: 88},
// {country: , sortOrder: 89},
// {country: , sortOrder: 90},
// {country: , sortOrder: 91},
// {country: , sortOrder: 92},
// {country: , sortOrder: 93},
// {country: , sortOrder: 94},
// {country: , sortOrder: 95},
// {country: , sortOrder: 96},
// {country: , sortOrder: 97},
// {country: , sortOrder: 98},
// {country: , sortOrder: 99},
// {country: , sortOrder: 100},
// {country: , sortOrder: 101},
// {country: , sortOrder: 102},
// {country: , sortOrder: 103},
// {country: , sortOrder: 104},
// {country: , sortOrder: 105},
// {country: , sortOrder: 106},
// {country: , sortOrder: 107},
// {country: , sortOrder: 108},
// {country: , sortOrder: 109},
// {country: , sortOrder: 110},
// {country: , sortOrder: 111},
// {country: , sortOrder: 112},
// {country: , sortOrder: 113},
// {country: , sortOrder: 114},
// {country: , sortOrder: 115},
// {country: , sortOrder: 116},
// {country: , sortOrder: 117},
// {country: , sortOrder: 118},
// {country: , sortOrder: 119},
// {country: , sortOrder: 120},
// {country: , sortOrder: 121},
// {country: , sortOrder: 122},
// {country: , sortOrder: 123},
// {country: , sortOrder: 124},
// {country: , sortOrder: 125},
// {country: , sortOrder: 126},
// {country: , sortOrder: 127},
// {country: , sortOrder: 128},
// {country: , sortOrder: 129},
// {country: , sortOrder: 130},
// {country: , sortOrder: 131},
// {country: , sortOrder: 132},
// {country: , sortOrder: 133},
// {country: , sortOrder: 134},
// {country: , sortOrder: 135},
// {country: , sortOrder: 136},
// {country: , sortOrder: 137},
// {country: , sortOrder: 138},
// {country: , sortOrder: 139},
// {country: , sortOrder: 140},
// {country: , sortOrder: 141},
// {country: , sortOrder: 142},
// {country: , sortOrder: 143},
// {country: , sortOrder: 144},
// {country: , sortOrder: 145},
// {country: , sortOrder: 146},
// {country: , sortOrder: 147},
// {country: , sortOrder: 148},
// {country: , sortOrder: 149},
// {country: , sortOrder: 150},
// {country: , sortOrder: 151},
// {country: , sortOrder: 152},
// {country: , sortOrder: 153},
// {country: , sortOrder: 154},
// {country: , sortOrder: 155},
// {country: , sortOrder: 156},
// {country: , sortOrder: 157},
// {country: , sortOrder: 158},
// {country: , sortOrder: 159},
// {country: , sortOrder: 160},
// {country: , sortOrder: 161},
// {country: , sortOrder: 162},
// {country: , sortOrder: 163},
// {country: , sortOrder: 164},
// {country: , sortOrder: 165},
// {country: , sortOrder: 166},
// {country: , sortOrder: 167},
// {country: , sortOrder: 168},
// {country: , sortOrder: 169},
// {country: , sortOrder: 170},
// {country: , sortOrder: 171},
// {country: , sortOrder: 172},
// {country: , sortOrder: 173},
// {country: , sortOrder: 174},
// {country: , sortOrder: 175},
// {country: , sortOrder: 176},
// {country: , sortOrder: 177},
// {country: , sortOrder: 178},
// {country: , sortOrder: 179},
// {country: , sortOrder: 180},
// {country: , sortOrder: 181},
// {country: , sortOrder: 182},
// {country: , sortOrder: 183},
// {country: , sortOrder: 184},
// {country: , sortOrder: 185},
// {country: , sortOrder: 186},
// {country: , sortOrder: 187},
// {country: , sortOrder: 188},
// {country: , sortOrder: 189},
// {country: , sortOrder: 190},
// {country: , sortOrder: 191},
// {country: , sortOrder: 192},
// {country: , sortOrder: 193},
// {country: , sortOrder: 194},
// {country: , sortOrder: 195},


,
,
'Antigua and Barbuda',
'Argentina',
'Armenia',
'Australia',
'Austria',
'Azerbaijan',
'Bahamas',
'Bahrain',
'Bangladesh',
'Barbados',
'Belarus',
'Belgium',
'Belize',
'Benin',
'Bhutan',
'Bolivia',
'Bosnia and Herzegovina',
'Botswana',
'Brazil',
'Brunei',
'Bulgaria',
'Burkina Faso',
'Burundi',
"Côte d'Ivoire",
'Cabo Verde',
'Cambodia',
'Cameroon',
'Canada',
'Central African Republic',
'Chad',
'Chile',
'China',
'Colombia',
'Comoros',
'Congo (Congo-Brazzaville)',
'Costa Rica',
'Croatia',
'Cuba',
'Cyprus',
'Czechia (Czech Republic)',
'Democratic Republic of the Congo',
'Denmark',
'Djibouti',
'Dominica',
'Dominican', 
'Republic',
'Ecuador',
'Egypt',
'El Salvador',
'Equatorial Guinea',
'Eritrea',
'Estonia',
'Eswatini (fmr. "Swaziland”)',
'Ethiopia',
'Fiji',
'Finland',
'France',
'Gabon',
'Gambia',
'Georgia',
'Germany',
'Ghana',
'Greece',
'Grenada',
'Guatemala',
'Guinea',
'Guinea-Bissau',
'Guyana',
'Haiti',
'Holy See',
'Honduras',
'Hungary',
'Iceland',
'India',
'Indonesia',
'Iran',
'Iraq',
'Ireland',
'Israel',
'Italy',
'Jamaica',
'Japan',
'Jordan',
'Kazakhstan',
'Kenya',
'Kiribati',
'Kuwait',
'Kyrgyzstan',
'Laos',
'Latvia',
'Lebanon',
'Lesotho',
'Liberia',
'Libya',
'Liechtenstein',
'Lithuania',
'Luxembourg',
'Madagascar',
'Malawi',
'Malaysia',
'Maldives',
'Mali',
'Malta',
'Marshall Islands',
'Mauritania',
'Mauritius',
'Mexico',
'Micronesia',
'Moldova',
'Monaco',
'Mongolia',
'Montenegro',
'Morocco',
'Mozambique',
'Myanmar (formerly Burma)',
'Namibia',
'Nauru',
'Nepal',
'Netherlands',
'New Zealand',
'Nicaragua',
'Niger',
'Nigeria',
'North Korea',
'North Macedonia',
'Norway',
'Oman',
'Pakistan',
'Palau',
'Palestine State',
'Panama',
'Papua New Guinea',
'Paraguay',
'Peru',
'Philippines',
'Poland',
'Portugal',
'Qatar',
'Romania',
'Russia',
'Rwanda',
'Saint Kitts and Nevis',
'Saint Lucia',
'Saint Vincent and the Grenadines',
'Samoa',
'San Marino',
'Sao Tome and Principe',
'Saudi Arabia',
'Senegal',
'Serbia',
'Seychelles',
'Sierra Leone',
'Singapore',
'Slovakia',
'Slovenia',
'Solomon Islands',
'Somalia',
'South Africa',
'South Korea',
'South Sudan',
'Spain',
'Sri Lanka',
'Sudan',
'Suriname',
'Sweden',
'Switzerland',
'Syria',
'Tajikistan',
'Tanzania',
'Thailand',
'Timor-Leste',
'Togo',
'Tonga',
'Trinidad and Tobago',
'Tunisia',
'Turkey',
'Turkmenistan',
'Tuvalu',
'Uganda',
'Ukraine',
'United Arab Emirates',
'United Kingdom',
'United States of America',
'Uruguay',
'Uzbekistan',
'Vanuatu',
'Venezuela',
'Vietnam',
'Yemen',
'Zambia',
'Zimbabwe']);

console.log(country)